spring:
  application:
    name: lv2-final-mission
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

  h2.console:
    enabled: true
    path: /h2-console
  datasource.url: jdbc:h2:mem:database


jwt:
  secret-key: WXmohJMCvigQggaEypa5E=Yn2kjibddFAWtnPJ2AFlL8
  validity-in-milliseconds: 1800000
cookie:
  max-age: 1800

---

spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: always
      data-locations:
  # h2-console
  h2.console:
    enabled: true
    path: /h2-console
  # db url
  datasource.url: jdbc:h2:mem:database



jwt:
  secret-key: WXmohJMCvigQggaEypa5E=Yn2kjibddFAWtnPJ2AFlL8
  validity-in-milliseconds: 1800000

cookie:
  max-age: 1800

